services:
  claude-proxy:
    build: .
    ports:
      - "${PORT:-8082}:8082"
    environment:
      - LITELLM_BASE_URL=${LITELLM_BASE_URL:-http://localhost:4000}
      - MODEL=${MODEL:-gpt-4o}
      - UPSTREAM_API_KEY=${UPSTREAM_API_KEY}
      - PORT=8082
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - NODE_ENV=${NODE_ENV:-production}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:8082/health').then(r => process.exit(r.ok ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
